include ../Makefile.inc

GEN_EXE = 4_1

LINUX_EXE = 

EXE = ${GEN_EXE} ${LINUX_EXE}

all : ${EXE}

allgen : ${GEN_EXE}

clean : 
	${RM} ${EXE} *.o

showall :
	@ echo ${EXE}

${EXE} : ${LDLIB}		# True as a rough approximation
